apiVersion: apps/v1
kind: Deployment

metadata:
  name: playlist-recommender-deployment
  labels:
    app: playlist-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      containers:
        - name: playlist-recommender
          image: yuseicarlos/playlist-recommender:v1.2.3
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 5000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-cs582
