apiVersion: apps/v1
kind: Deployment

metadata:
  name: playlist-recommender-deployment
  labels:
    app: playlist-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      containers:
        - name: playlist-recommender
          image: yuseicarlos/playlist-recommender:v1.0
          ports:
            - containerPort: 5000
