apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: yuseicarlos/ml-model:v1.2.4
          env:
            - name: DATASET_FILE
              value: "~/home/datasets/playlist-sample-ds1.csv"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-cs582