apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: yuseicarlos/ml-model:v1.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: project2-pv-cs582
              mountPath: /
      volumes:
        - name: project2-pv-cs582
          persistentVolumeClaim:
            claimName: pvc-recommender
