apiVersion: v1
kind: Pod
metadata:
  name: ml-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: ml-model
      image: yuseicarlos/ml-model:v1.0
      ports:
        - containerPort: 5000
