apiVersion: v1
kind: Pod
metadata:
  name: ml-model-pod-2
spec:
  restartPolicy: OnFailure
  containers:
    - name: ml-model-deployment
      image: yuseicarlos/ml-model:v1.2.10
      command: [ "python3", "train.py" ]
      volumeMounts:
        - name: data
          mountPath: /data
      env:
        - name: DATASET_CSV
          value: https://github.com/cs582/recommenderDatasets/blob/main/playlist-sample-ds2.csv
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-cs582
