apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs582
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: standard
  volumeName: project2-pv-cs582
  volumeMode: Filesystem
  selector:
    matchLabels:
      type: local