apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs582
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: standard
  volumeName: project2-pv-cs582