apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs582
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: project2-pv-cs582