apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs582
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: standard
  volumeMode: Filesystem
  selector:
    matchLabels:
      type: local