apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-recommender
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
    selector:
      matchLabels:
        type: local